name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0 #4.3.2+2
  cloud_firestore: ^1.0.7 #0.12.9
  firebase_core: ^1.1.0 #0.4.0+8
  flutter_bloc: ^7.0.0 #6.0.6
  meta: ^1.3.0 #1.1.6
  bloc: ^7.0.0 #6.0.3
  # equatable: ^2.0.0 #1.0.2
  fluttertoast: ^8.0.6 #7.1.1
  cached_network_image: ^3.0.0 #2.3.3
  google_fonts: ^2.0.0
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8 #0.1.9

flutter_native_splash:
  image: assets/images/logo.png
  color: "#5E92F3"
  web: false
  fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/books/
    - assets/images/logo.png
    - assets/images/2.0x/logo.png
    - assets/images/3.0x/logo.png
