name: api_sdk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.1
  cloud_firestore: ^1.0.7 #0.12.9
  firebase_core: ^1.1.0 #0.4.0+8
  firebase_auth: ^1.1.2 #empty
  # get_it: ^6.1.1 #1.0.3+2

  # equatable: ^2.0.0 #1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
